version: '3.8'

services:
  api:
    build: .
    container_name: vibe-coding-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - ./app:/app/app:ro  # Read-only for security
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - vibe-network

  # Future services can be added here
  # redis:
  #   image: redis:7-alpine
  #   container_name: vibe-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - vibe-network

  # postgres:
  #   image: postgres:15-alpine
  #   container_name: vibe-postgres
  #   environment:
  #     POSTGRES_DB: vibe_coding
  #     POSTGRES_USER: vibe_user
  #     POSTGRES_PASSWORD: vibe_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - vibe-network

networks:
  vibe-network:
    driver: bridge

# volumes:
#   redis_data:
#   postgres_data: